name: Build and push Assistant Docker image to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name acrstrategiaapp.azurecr.io

      - name: Define Tag
        id: vars
        run: echo "TAG=${{ github.run_number }}-${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        env:
          REGISTRY: acrstrategiaapp.azurecr.io
          IMAGE_NAME: app-strategia-wsp
          TAG: ${{ env.TAG }}
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$TAG .
          docker push $REGISTRY/$IMAGE_NAME:$TAG


      - name: Update Assistant application
        env:
          REGISTRY: acrstrategiaapp.azurecr.io
          IMAGE_NAME: app-strategia-wsp
          TAG: ${{ env.TAG }}      
        run: |
          az webapp config container set \
            --name app-assistant-wsp \
            --resource-group rg-strategia-app \
            --docker-custom-image-name $REGISTRY/$IMAGE_NAME:$TAG \
            --docker-registry-server-url https://acrstrategiaapp.azurecr.io \
            --docker-registry-server-user acrstrategiaapp \
            --docker-registry-server-password oJC8SIrSBSXydRCDvB5lXEaTM059L/PvVD9v9qzjgy+ACRDbWoRY

      - name: Stop Azure Web App
        run: |
          az webapp stop \
            --name app-assistant-wsp \
            --resource-group rg-strategia-app

      - name: Start Azure Web App
        run: |
          az webapp start \
            --name app-assistant-wsp \
            --resource-group rg-strategia-app
